services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 777 #루트 계정의 비밀번호
      MYSQL_DATABASE: testdb #생성할 데이터베이스 이름
      MYSQL_USER: jin #접속할 아이디
      MYSQL_PASSWORD: 123 #접속할 비밀번호
    ports:
      - "3306:3306"
    volumes: # volumes 사용 선언
      - mysql_data:/var/lib/mysql # 위치A:위치B - 위치B를 위치A에 할당해주는 작업

volumes: # volume 정의
  mysql_data: